### PR TITLE
pc fix

### PR DESCRIPTION
**Pull request by karthikbr82**

### CODE REVIEW

**Comment by karthikbr82** [comment]
@danjenkins PTAL

**Comment by karthikbr82** [comment]
We could not test the audio mute and unmute, and the addNewFabric uses peerConnection._peerConnection._peerConnection, may be it was typo or something. I dont think twilio has changed anything here.

**Comment by kscherling** [comment]
Awesome.  Will test this now...
👍

**Comment by kscherling** [comment]
@danjenkins Previously the sessions were being logged to callstats successfully.  However, any peerConnection events ie mute, video disable, track disconnect were generating errors and not logging.  The update now shows all events on the timeline and no more errors are present. 

🎉 
screen shot 2017-11-29 at 11 17 29 am

**Review by kscherling — APPROVED** [review]
Works like a charm.  Thanks for the quick turn around on this fellas.

**Pull request merged**
